const express = require('express');
const router = express.Router();
const exteriorController = require('../controllers/exterior.controller');
const upload = require('../config/upload');

router.post('/', upload.fields([
    { name: 'frontLeftImage', maxCount: 1 },
    { name: 'frontImage', maxCount: 1 },
    { name: 'frontRightImage', maxCount: 1 },
    { name: 'grill', maxCount: 1 },
    { name: 'windowScreenGlassFront', maxCount: 1 },
    { name: 'bonnetHood', maxCount: 1 },
    { name: 'windScreenWiperFront', maxCount: 1 },
    { name: 'headlightRH', maxCount: 1 },
    { name: 'frontRightIndicator', maxCount: 1 },
    { name: 'headlightLH', maxCount: 1 },
    { name: 'frontLeftIndicator', maxCount: 1 },
    { name: 'headlampSupport', maxCount: 1 },
    { name: 'parkingLightFront', maxCount: 1 },
    { name: 'bonnetPatti', maxCount: 1 },
    { name: 'rightImage', maxCount: 1 },
    { name: 'apron', maxCount: 1 },
    { name: 'rhSideApron', maxCount: 1 },
    { name: 'alloyWheels', maxCount: 1 },
    { name: 'alloyWheelsFrontRHS', maxCount: 1 },
    { name: 'alloyWheelsRearRHS', maxCount: 1 },
    { name: 'alloyWheelsFrontLHS', maxCount: 1 },
    { name: 'alloyWheelsRearLHS', maxCount: 1 },
    { name: 'steelWheelRimRearRHS', maxCount: 1 },
    { name: 'steelWheelRimFrontRHS', maxCount: 1 },
    { name: 'steelWheelRimRearLHS', maxCount: 1 },
    { name: 'steelWheelRimFrontLHS', maxCount: 1 },
    { name: 'tyreFrontRH', maxCount: 1 },
    { name: 'tyreFrontRHImage', maxCount: 1 },
    { name: 'rhRearViewMirror', maxCount: 1 },
    { name: 'rhQuarterPanel', maxCount: 1 },
    { name: 'rhFinder', maxCount: 1 },
    { name: 'rhAPillar', maxCount: 1 },
    { name: 'frontRHDoor', maxCount: 1 },
    { name: 'rhBPillar', maxCount: 1 },
    { name: 'rearRHDoor', maxCount: 1 },
    { name: 'rhCPillar', maxCount: 1 },
    { name: 'rhRunningBoard', maxCount: 1 },
    { name: 'tyreRearRH', maxCount: 1 },
    { name: 'tyreRearRHImage', maxCount: 1 },
    { name: 'imageRearRight', maxCount: 1 },
    { name: 'imageRear', maxCount: 1 },
    { name: 'imageRearLeft', maxCount: 1 },
    { name: 'imageRearBumper', maxCount: 1 },
    { name: 'tailLightRH', maxCount: 1 },
    { name: 'tailLightLH', maxCount: 1 },
    { name: 'dickky', maxCount: 1 },
    { name: 'dickkyBootfloor', maxCount: 1 },
    { name: 'spareWheel', maxCount: 1 },
    { name: 'spareWheelImage', maxCount: 1 },
    { name: 'windscreenGlassBack', maxCount: 1 },
    { name: 'windScreenWiperRear', maxCount: 1 },
    { name: 'wheelCap', maxCount: 1 },
    { name: 'reverseCameraAndParkingSensor', maxCount: 1 },
    { name: 'leftImage', maxCount: 1 },
    { name: 'tyreRearLH', maxCount: 1 },
    { name: 'tyreRearLHImage', maxCount: 1 },
    { name: 'lhRunningBoard', maxCount: 1 },
    { name: 'lhCPillar', maxCount: 1 },
    { name: 'rearLHDoor', maxCount: 1 },
    { name: 'lhBPillar', maxCount: 1 },
    { name: 'frontLHDoor', maxCount: 1 },
    { name: 'lhAPillar', maxCount: 1 },
    { name: 'lhFinder', maxCount: 1 },
    { name: 'lhQuarterPanel', maxCount: 1 },
    { name: 'tyreFrontLH', maxCount: 1 },
    { name: 'tyreFrontLHImage', maxCount: 1 },
    { name: 'lhRearViewMirror', maxCount: 1 },
    { name: 'lhSideApron', maxCount: 1 },
    { name: 'firewall', maxCount: 1 },
    { name: 'underbody', maxCount: 1 },
    { name: 'roof', maxCount: 1 },
    { name: 'roofImage', maxCount: 1 }
]), exteriorController.createExterior);

router.get('/:id', exteriorController.getExteriorById);
router.get('/', exteriorController.getAllExteriors);

module.exports = router;
