const mongoose = require('mongoose');

const exteriorSchema = new mongoose.Schema({
    frontLeftImage: { type: String, required: true },
    frontImage: { type: String, required: true },
    frontRightImage: { type: String, required: true },
    grill: { type: String, required: true },
    windowScreenGlassFront: { type: String, required: true },
    bonnetHood: { type: String, required: true },
    windScreenWiperFront: { type: String, required: true },
    headlightRH: { type: String, required: true },
    frontRightIndicator: { type: String, required: true },
    headlightLH: { type: String, required: true },
    frontLeftIndicator: { type: String, required: true },
    headlampSupport: { type: String, required: true },
    parkingLightFront: { type: String, required: true },
    bonnetPatti: { type: String, required: true },
    rightImage: { type: String, required: true },
    apron: { type: String, required: true },
    rhSideApron: { type: String, required: true },
    alloyWheels: { type: String, required: true },
    alloyWheelsFrontRHS: { type: String, required: true },
    alloyWheelsRearRHS: { type: String, required: true },
    alloyWheelsFrontLHS: { type: String, required: true },
    alloyWheelsRearLHS: { type: String, required: true },
    steelWheelRimRearRHS: { type: String, required: true },
    steelWheelRimFrontRHS: { type: String, required: true },
    steelWheelRimRearLHS: { type: String, required: true },
    steelWheelRimFrontLHS: { type: String, required: true },
    tyreFrontRH: { type: String, required: true },
    tyreFrontRHImage: { type: String, required: true },
    rhRearViewMirror: { type: String, required: true },
    rhQuarterPanel: { type: String, required: true },
    rhFinder: { type: String, required: true },
    rhAPillar: { type: String, required: true },
    frontRHDoor: { type: String, required: true },
    rhBPillar: { type: String, required: true },
    rearRHDoor: { type: String, required: true },
    rhCPillar: { type: String, required: true },
    rhRunningBoard: { type: String, required: true },
    tyreRearRH: { type: String, required: true },
    tyreRearRHImage: { type: String, required: true },
    imageRearRight: { type: String, required: true },
    imageRear: { type: String, required: true },
    imageRearLeft: { type: String, required: true },
    imageRearBumper: { type: String, required: true },
    tailLightRH: { type: String, required: true },
    tailLightLH: { type: String, required: true },
    dickky: { type: String, required: true },
    dickkyBootfloor: { type: String, required: true },
    spareWheel: { type: String, required: true },
    spareWheelImage: { type: String, required: true },
    windscreenGlassBack: { type: String, required: true },
    windScreenWiperRear: { type: String, required: true },
    wheelCap: { type: String, required: true },
    reverseCameraAndParkingSensor: { type: String, required: true },
    leftImage: { type: String, required: true },
    tyreRearLH: { type: String, required: true },
    tyreRearLHImage: { type: String, required: true },
    lhRunningBoard: { type: String, required: true },
    lhCPillar: { type: String, required: true },
    rearLHDoor: { type: String, required: true },
    lhBPillar: { type: String, required: true },
    frontLHDoor: { type: String, required: true },
    lhAPillar: { type: String, required: true },
    lhFinder: { type: String, required: true },
    lhQuarterPanel: { type: String, required: true },
    tyreFrontLH: { type: String, required: true },
    tyreFrontLHImage: { type: String, required: true },
    lhRearViewMirror: { type: String, required: true },
    lhSideApron: { type: String, required: true },
    firewall: { type: String, required: true },
    underbody: { type: String, required: true },
    roof: { type: String, required: true },
    roofImage: { type: String, required: true },
    createdAt: {
        type: Date,
        default: Date.now,
    }
});

const Exterior = mongoose.model('Exterior', exteriorSchema);

module.exports = Exterior;
